// Movie data stored in a separate file
const movies = [
        {
            "title": "THE TALE OF THE PRINCESS KAGUYA",
            "year": "2013",
            "length": "137 minutes",
            "genre": "Fantasy, Drama",
            "themes": "Life, Mortality, Nature",
            "director": "Isao Takahata",
            "studio": "Studio Ghibli",
            "description": "Kaguya is a beautiful young woman coveted by five nobles. To try to avoid marrying a stranger she doesn't love, she sends her suitors on seemingly impossible tasks. But she will have to face her fate and punishment for her choices.",
            "awards": "Academy Award Nominee for Best Animated Feature",
            "rottenTomatoes": "100% (Certified Fresh)",
            "imdb": "8.0/10",
            "poster": "./media/Movies/the_tale_of_the_princess_kaguya.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/Ed9l4gtI5H5GgQ-zgc3Z9fsBmC4xnSSWGY3MSJwr7cV-kQ?download=1"
        },
        {
            "title": "SPIRITED AWAY",
            "year": "2001",
            "length": "125 minutes",
            "genre": "Fantasy, Adventure",
            "themes": "Coming of age, Greed, Environmentalism",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "A young girl gets trapped in a mysterious, magical world and must find a way to save her parents and return home.",
            "awards": "Academy Award for Best Animated Feature, Golden Bear at Berlin International Film Festival",
            "rottenTomatoes": "96% (Certified Fresh)",
            "imdb": "8.6/10",
            "poster": "./media/Movies/spirited_away.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/ES7nOLIdvdJEmPaZ0ZSo5UUBaclXOXvpRQjSpmam4bVPFw?download=1"
        },
        {
            "title": "WHEN MARNIE WAS THERE",
            "year": "2014",
            "length": "103 minutes",
            "genre": "Drama, Fantasy, Mystery",
            "themes": "Friendship, Loneliness, Memory",
            "director": "Hiromasa Yonebayashi",
            "studio": "Studio Ghibli",
            "description": "Anna, a shy 12-year-old girl, is sent to spend time with her aunt and uncle who live in the countryside, where she meets Marnie. The two become best friends. But Anna gradually discovers that Marnie is not quite who she appears to be.",
            "awards": "Tokyo Anime Award, Japan Academy Prize for Animation of the Year",
            "rottenTomatoes": "92% (Certified Fresh)",
            "imdb": "7.6/10",
            "poster": "./media/Movies/when_marnie_was_there.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EUsB6jd7oVRNjMnrxd2-amABUu1GEayqQu326qijo3fXyQ?download=1"
        },
        {
            "title": "GRAVE OF THE FIREFLIES",
            "year": "1988",
            "length": "89 minutes",
            "genre": "War, Drama",
            "themes": "Survival, Loss, Sibling Bond",
            "director": "Isao Takahata",
            "studio": "Studio Ghibli",
            "description": "The story of two siblings struggling to survive during the final months of World War II in Japan, facing the harsh realities of war and loss.",
            "awards": "Mainichi Film Award for Best Animation Film, Animage Anime Grand Prix",
            "rottenTomatoes": "100% (Certified Fresh)",
            "imdb": "8.5/10",
            "poster": "./media/Movies/grave_of_the_fireflies.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EQVRoMwCz6NHudZrSrX6zCoBl0uQgTpQW2FvhlJwuIpF0w?download=1"
        },
        {
            "title": "PRINCESS MONONOKE",
            "year": "1997",
            "length": "133 minutes",
            "genre": "Fantasy, Drama",
            "themes": "Nature, Industrialization, War",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.",
            "awards": "Nominated for the Academy Award for Best Animated Feature",
            "rottenTomatoes": "93% (Certified Fresh)",
            "imdb": "8.3/10",
            "poster": "./media/Movies/princess_mononoke.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/ERLIO1TqN7RHhcV-SPr00IYB0Ix4_zjZ_6xX4hgc5QzvnA?download=1"
        },
        {
            "title": "THE SECRET WORLD OF ARRIETTY",
            "year": "2010",
            "length": "94 minutes",
            "genre": "Fantasy, Adventure, Drama",
            "themes": "Friendship, Courage, Isolation, Perspective",
            "director": "Hiromasa Yonebayashi",
            "studio": "Studio Ghibli",
            "description": "The Clock family are four-inch-tall people who live anonymously in another family's residence, borrowing simple items to make their home. Life changes for the Clocks when their teenage daughter Arrietty is discovered.",
            "awards": "Tokyo Anime Award, Annie Award nomination for Best Animated Feature",
            "rottenTomatoes": "94% (Certified Fresh)",
            "imdb": "7.6/10",
            "poster": "./media/Movies/the_secret_world_of_arrietty.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EcQRQaSNJpNGkFT9EOf9rjoBJlVgrkxgyBephhu6r0MYnQ?download=1"
        },
        {
            "title": "POM POKO",
            "year": "1994",
            "length": "119 minutes",
            "genre": "Fantasy, Drama, Comedy",
            "themes": "Environmentalism, Change, Loss, Nature",
            "director": "Isao Takahata",
            "studio": "Studio Ghibli",
            "description": "A community of magical shape-shifting raccoon dogs struggle to prevent their forest home from being destroyed by urban development.",
            "awards": "Japan Academy Prize for Best Animation",
            "rottenTomatoes": "86% (Certified Fresh)",
            "imdb": "7.3/10",
            "poster": "./media/Movies/pom_poko.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EfkTUHfJB11EqxU9c15lTH8BoMmioSI3TSoStBiKymxymg?download=1"
        },
        {
            "title": "ONLY YESTERDAY",
            "year": "1991",
            "length": "119 minutes",
            "genre": "Drama, Romance",
            "themes": "Nostalgia, Self-discovery, Feminism, Childhood",
            "director": "Isao Takahata",
            "studio": "Studio Ghibli",
            "description": "A 27-year-old woman looks back on her childhood and reflects on the choices she made, while also coming to terms with her current life and desires.",
            "awards": "Japan Academy Prize for Best Animation",
            "rottenTomatoes": "100% (Certified Fresh)",
            "imdb": "7.6/10",
            "poster": "./media/Movies/only_yesterday.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EZ71x_xZfbVFmYN1MGZs5GwB4YU8jB7oU4IWeU2QBx0vVw?download=1"
        },
        {
            "title": "MY NEIGHBOR TOTORO",
            "year": "1988",
            "length": "86 minutes",
            "genre": "Fantasy, Family",
            "themes": "Childhood, Nature, Family",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "Two young girls discover a magical creature, Totoro, and embark on whimsical adventures in the countryside.",
            "awards": "Nominated for multiple awards, including the Academy Award for Best Animated Feature",
            "rottenTomatoes": "94% (Certified Fresh)",
            "imdb": "8.1/10",
            "poster": "./media/Movies/my_neighbor_totoro.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/ETgNyfqMGgBDkoFN7yBWQSoBbtMzoPnKJSHJmw7WIDxjkg?download=1"
        },
        {
            "title": "THE WIND RISES",
            "year": "2013",
            "length": "126 minutes",
            "genre": "Biographical, Drama, Romance",
            "themes": "Dreams, War, Love, Sacrifice",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "The story of Jiro Horikoshi, the engineer behind Japan's World War II aircraft, and his struggles to balance dreams with reality.",
            "awards": "Academy Award Nominee for Best Animated Feature",
            "rottenTomatoes": "88% (Certified Fresh)",
            "imdb": "7.8/10",
            "poster": "./media/Movies/the_wind_rises.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/ERMrCEGmXjpJoEOoN4FzfogB8S52xH9Zou2Biozp8eOPIA?download=1"
        },
        {
            "title": "NAUSICAA OF THE VALLEY OF THE WIND",
            "year": "1984",
            "length": "117 minutes",
            "genre": "Fantasy, Adventure",
            "themes": "Environmentalism, War, Peace",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "Nausicaä, a princess in a post-apocalyptic world, strives to protect her people and the environment from toxic forests and war.",
            "awards": "Nominated for several awards, including the Animage Anime Awards",
            "rottenTomatoes": "91% (Certified Fresh)",
            "imdb": "8.0/10",
            "poster": "./media/Movies/nausicaa.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EeU3hcDizWBMtA6NN9oQLxUBL5gHWZj9_Z6a7pHNCV2ivg?download=1"
        },
        {
            "title": "PONYO",
            "year": "2008",
            "length": "115 minutes",
            "genre": "Fantasy, Adventure",
            "themes": "Friendship, Nature, Love",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "A five-year-old boy develops a relationship with Ponyo, a young goldfish princess who longs to become a human after falling in love with him.",
            "awards": "Nominated for an Academy Award for Best Animated Feature",
            "rottenTomatoes": "91% (Certified Fresh)",
            "imdb": "7.6/10",
            "poster": "./media/Movies/ponyo.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/ER3m1Eu701tIu-QPvKQEO1EBqllmsSLStZIYdumA5zKM0Q?download=1"
        },
        {
            "title": "KIKI'S DELIVERY SERVICE",
            "year": "1989",
            "length": "102 minutes",
            "genre": "Fantasy, Adventure, Family",
            "themes": "Independence, Self-discovery, Growing up",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "Along with her black cat Jiji, Kiki settles in a seaside town and starts a high-flying delivery service. Here begins her magical encounter with independence and responsibility, making lifelong friends and finding her place in the world.",
            "awards": "Nominated for a Golden Bear at the Berlin Film Festival",
            "rottenTomatoes": "98% (Certified Fresh)",
            "imdb": "7.8/10",
            "poster": "./media/Movies/kiki_delivery_service.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EaA1U_h-j7tKq8Bjm93x_zYBMCOjrwyub-Xvhh8M9tqwcA?download=1"
        },
        {
            "title": "MY NEIGHBORS THE YAMADAS",
            "year": "1999",
            "length": "104 minutes",
            "genre": "Comedy, Family",
            "themes": "Family Life, Humor, Everyday Struggles",
            "director": "Isao Takahata",
            "studio": "Studio Ghibli",
            "description": "A humorous, episodic look at the life of the Yamada family, exploring their daily experiences and interactions in a lighthearted, often comedic way.",
            "awards": "Japan Academy Prize for Animation of the Year",
            "rottenTomatoes": "78% (Fresh)",
            "imdb": "7.1/10",
            "poster": "./media/Movies/my_neighbors_the_yamadas.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EfVASC_lZS9IlMv0Lb3bynsBuCox4pZ7ve8-zVEHzJ-m_w?download=1"
        },
        {
            "title": "PORCO ROSSO",
            "year": "1992",
            "length": "94 minutes",
            "genre": "Adventure, Drama, Fantasy",
            "themes": "War, Identity, Isolation, Love",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "A former World War I pilot, cursed to live as a pig, becomes a bounty hunter in 1930s Italy while grappling with his past and the effects of war.",
            "awards": "Animage Anime Grand Prix (1992)",
            "rottenTomatoes": "96% (Certified Fresh)",
            "imdb": "7.7/10",
            "poster": "./media/Movies/porco_rosso.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/ES5WeGpfQGhMrsGyV4tNUhwBd1dvIVh05GSwR7oRpTtg0w?download=1"
        },
        {
            "title": "HOWL'S MOVING CASTLE",
            "year": "2004",
            "length": "119 minutes",
            "genre": "Fantasy, Romance",
            "themes": "War, Self-discovery, Love",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.",
            "awards": "Academy Award Nominee for Best Animated Feature",
            "rottenTomatoes": "88% (Certified Fresh)",
            "imdb": "8.2/10",
            "poster": "./media/Movies/howl_moving_castle.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EZXwbiejujdJi_uLy6_55sQB-fZMjqih_KdO-GfEzx4COg?download=1"
        },
        {
            "title": "CASTLE IN THE SKY",
            "year": "1986",
            "length": "124 minutes",
            "genre": "Adventure, Fantasy",
            "themes": "Friendship, Adventure, Greed",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "Pazu's life changes when he meets Sheeta, a girl whom pirates are chasing for her crystal amulet, which has the potential to locate Laputa, a legendary castle floating in the sky.",
            "awards": "Nominated for the Japan Academy Prize for Animation of the Year",
            "rottenTomatoes": "96% (Certified Fresh)",
            "imdb": "8.0/10",
            "poster": "./media/Movies/castle_in_the_sky.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EXcwNPy-2ulCutEp8NQBSB0BfOhSQibnO4X3wcn4LHQjeQ?download=1"
        },
        {
            "title": "WHISPER OF THE HEART",
            "year": "1995",
            "length": "111 minutes",
            "genre": "Romance, Drama",
            "themes": "Dreams, Self-discovery, Love",
            "director": "Yoshifumi Kondo", 
            "studio": "Studio Ghibli",
            "description": "A love story between a girl who loves reading books, and a boy who has previously checked out all of the library books she chooses.",
            "awards": "Nominated for the Japan Academy Prize for Animation of the Year",
            "rottenTomatoes": "95% (Certified Fresh)",
            "imdb": "7.8/10",
            "poster": "./media/Movies/whisper_of_the_heart.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EZ1KDF28KYtMpVQZ-vWYS-wB0ouzcMvMmzmLGi83-Iw9gA?download=1"
        },
        {
            "title": "FROM UP ON POPPY HILL",
            "year": "2011",
            "length": "91 minutes",
            "genre": "Drama, Romance",
            "themes": "Love, Family, Coming of Age, Nostalgia",
            "director": "Goro Miyazaki",
            "studio": "Studio Ghibli",
            "description": "A group of Yokohama teens look to save their school's clubhouse from the wrecking ball in preparations for the 1964 Tokyo Olympics.",
            "awards": "Tokyo Anime Award (2012)",
            "rottenTomatoes": "87% (Certified Fresh)",
            "imdb": "7.4/10",
            "poster": "./media/Movies/from_up_on_poppy_hill.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EV_IUYrZ6cZDswLg_5bwlbkBD4Q5hM3zcwMlkhX6ULUmpA?download=1"
        },
        {
            "title": "TALES FROM EARTHSEA",
            "year": "2006",
            "length": "115 minutes",
            "genre": "Fantasy, Adventure",
            "themes": "Power, Death, Identity, Fate",
            "director": "Goro Miyazaki",
            "studio": "Studio Ghibli",
            "description": "Based on the Earthsea book series by Ursula K. Le Guin, the film follows a young prince and a wizard as they journey through a land plagued by a mysterious imbalance in the world.",
            "awards": "Tokyo Anime Award (2007)",
            "rottenTomatoes": "37%",
            "imdb": "6.3/10",
            "poster": "./media/Movies/tales_from_earthsea.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EcLg1O26witAjNUsMqUwe1gBXVyY-_Tp0gXZTtsApFW50Q?download=1"
        },
        {
            "title": "THE CAT RETURNS",
            "year": "2002",
            "length": "75 minutes",
            "genre": "Fantasy, Adventure, Family",
            "themes": "Friendship, Courage, Self-worth",
            "director": "Hiroyuki Morita",
            "studio": "Studio Ghibli",
            "description": "After helping a cat, a seventeen-year-old girl finds herself involuntarily engaged to a cat Prince in a magical world where her only hope of freedom lies with a dapper cat statuette come to life.",
            "awards": "Nominated for Best Animation at the Tokyo International Film Festival",
            "rottenTomatoes": "88%",
            "imdb": "7.1/10",
            "poster": "./media/Movies/the_cat_returns.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EbkcaLKIYxZJvZDffPwc26AB3nKwILljI3i8gdDYuYCtTA?download=1"
        },
        {
            "title": "OCEAN WAVES",
            "year": "1993",
            "length": "72 minutes",
            "genre": "Romance, Drama",
            "themes": "Adolescence, Love, Friendship",
            "director": "Tomomi Mochizuki",
            "studio": "Studio Ghibli",
            "description": "A teenage boy recalls his high school days in a small seaside town, focusing on his complicated relationship with a new girl in town and the dynamics of their friendship.",
            "awards": "Nominated for the Annecy International Animated Film Festival (1994)",
            "rottenTomatoes": "89%",
            "imdb": "6.6/10",
            "poster": "./media/Movies/ocean_waves.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EcKJo-H5qzxOpehIonvaI0EBrsJB0i6rI0BuEBF60hkuCw?download=1"
        },
        {
            "title": "THE BOY AND THE HERON",
            "year": "2023",
            "length": "122 minutes",
            "genre": "Fantasy, Adventure, Drama",
            "themes": "Grief, Imagination, Coming of Age",
            "director": "Hayao Miyazaki",
            "studio": "Studio Ghibli",
            "description": "In the wake of his mother's death and his father's remarriage, a headstrong boy ventures into a dreamlike world shared by the living and the dead in search of his missing stepmother.",
            "awards": "Academy Award® for Best Animated Feature",
            "rottenTomatoes": "96% (Certified Fresh)",
            "imdb": "7.4/10",
            "poster": "./media/Movies/the_boy_and_the_heron.jpg",
            "trailer": "https://ikelte-my.sharepoint.com/:v:/g/personal/ec9vqv_inf_elte_hu/EffzNFzLxP5Lk9ztx4ofOsoBse3U46WT5AWpREmTqHU02Q?download=1"
        }
];